# inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.6.4
  Exclude:
    - app/channels/**/*
    - node_modules/**/*
    - bin/*
    - test/**/*
    - spec/**/*
    - lib/*
    - db/migrate/*
    - db/schema.rb
    - lib/tasks/*
    - public/*
    - tmp/*
    - vendor/**/*
    - config/spring.rb
    - config/unicorn.rb
    - config/unicorn_staging.rb
    - tmp/**/*

Rails/FilePath:
  Exclude:
    - 'config/environments/development.rb'

Rails/InverseOf:
  Exclude:
    - 'app/models/micropost.rb'
    - 'app/models/user.rb'

Layout/LineLength:
  Description: 'This cop checks the length of lines in the source code.'
  Max: 200

Metrics/BlockLength:
  Max: 46

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 25

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/GlobalVars:
  Exclude:
    - 'config/unicorn.conf.rb'
    - 'config/unicorn/production.rb'

Style/ClassAndModuleChildren:
  Description: 'This cop checks the style of children definitions at classes and modules.'
  EnforcedStyle: compact
  Exclude:
    - 'config/application.rb'

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/SuppressedException:
  Exclude:
    - 'config/unicorn.conf.rb'
    - 'config/unicorn/production.rb'
