version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
        environment:
          BUNDLER_VERSION: 2.1.4
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
          DB_USERNAME: 'root'
          DB_PASSWORD: ''

      - image: circleci/mysql:5.7
        environment:
          MYSQL_DATABASE: The_Trip_Tip_test

    working_directory: ~/The_Trip_Tip

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
            - rails-demo-yarn-{{ checksum "yarn.lock" }}
            - rails-demo-yarn-

      - run:
          name: install dependencies
          command: |
            gem install bundler -v 2.1.4
            bundle install --jobs=4 --retry=3 --path vendor/bundle
            yarn install --cache-folder ~/.cache/yarn

      - save_cache:
          paths:
            - ./vendor/bundle
            - node_modules
          key: app-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}

      - run: mv ./config/database.yml.ci ./config/database.yml
      - run: bundle exec rake db:create --trace
      - run: bundle exec rake db:schema:load
      - run: bundle exec bin/webpack

      - run:
          name: run rubocop
          command: bundle exec rubocop

      - run:
          name: run rspec
          command: bundle exec rspec

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
