version: 2.1

references:
  defaults: &defaults
    working_directory: ~/The_Trip_Tip

  ruby_docker_image: &ruby_docker_image
    image: circleci/ruby:2.6.5-node-browsers
    environment:
      BUNDLER_VERSION: 2.1.4
      RAILS_ENV: test
      MYSQL_HOST: 127.0.0.1
      MYSQL_USERNAME: 'root'
      MYSQL_PASSWORD: ''
      MYSQL_PORT: 3306

  restore_code_cache: &restore_code_cache
    restore_cache:
      keys:
        - v-repo-{{ .Environment.CIRCLE_SHA1 }}

  restore_gem_cache: &restore_gem_cache
    restore_cache:
      keys:
        - v1-dependencies-{{ checksum "Gemfile.lock" }}
        - v1-dependencies-

  restore_node_module_cache: &restore_node_module_cache
    restore_cache:
      keys:
        - v1-dependencies-yarn-{{ checksum "yarn.lock" }}
        - v1-dependencies-yarn

jobs:
  checkout_code:
    <<: *defaults
    docker:
      - *ruby_docker_image
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/project

  test:
    <<: *defaults
    docker:
      - *ruby_docker_image
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
    steps:
      - checkout
      - *restore_code_cache
      - *restore_gem_cache
      - *restore_node_module_cache

      - run: gem install bundler -v 2.1.4
      - run: bundle install --path vendor/bundle --clean
      - run: yarn install --check-files

      - run: mv -f ./config/database.yml.ci ./config/database.yml
      - run: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run: bundle exec rake db:create db:schema:load --trace

      - run: bundle exec bin/webpack

      - run: bundle exec rubocop
      - run: bundle exec rspec
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

  deploy:
    <<: *defaults
    docker:
      - *ruby_docker_image
    steps:
      - checkout
      - *restore_code_cache
      - *restore_gem_cache
      - *restore_node_module_cache

      - run: gem install bundler -v 2.1.4
      - run: bundle install --path vendor/bundle --clean
      - run: yarn install --check-files
      - add_ssh_keys:
          fingerprints:
            - '23:1f:a5:a5:cd:54:71:f6:fc:7b:5c:a1:b5:07:5f:80'
      - deploy:
          name: Capistrano deploy
          command: bundle exec cap production deploy

workflows:
  version: 2.1
  test_and_deploy:
    jobs:
      - checkout_code
      - test:
          requires:
            - checkout_code
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
