default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  host: 127.0.0.1

development:
  <<: *default
  database: The_Trip_Tip_development
  socket: /tmp/mysql.sock

test:
  <<: *default
  database: The_Trip_Tip_test
  socket: /tmp/mysql.sock

production:
  <<: *default
  pool: 5
  database: The_Trip_Tip_production
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock
