default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: The_Trip_Tip_development

test:
  <<: *default
  database: The_Trip_Tip_test

production:
  <<: *default
  pool: 5
  database: The_Trip_Tip_production
  username: root
  password:
  host: 127.0.0.1
  socket: /var/lib/mysql/mysql.sock
