default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: password
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: The_Trip_Tip_development
  host: db

test:
  <<: *default
  database: The_Trip_Tip_test
  host: db

production:
  <<: *default
  database: The_Trip_Tip_production
  username: root
  password:
  host: 127.0.0.1
  socket: /var/lib/mysql/mysql.sock
