default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: password
  host: db
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: The_Trip_Tip_development

test:
  <<: *default
  database: The_Trip_Tip_test

production:
  <<: *default
  pool: 5
  database: The_Trip_Tip_production
  username: root
  password: XkZJbdYj
  socket: /var/lib/mysql/mysql.sock
  host: thetriptip-mysql.cagpvf21wtdj.ap-northeast-1.rds.amazonaws.com
