# default: &default
#   adapter: mysql2
#   encoding: utf8
#   pool: 5
#   username: root
#   password: password
#   host: db
#   socket: /tmp/mysql.sock

# development:
#   <<: *default
#   database: The_Trip_Tip_development

# test:
#   <<: *default
#   database: The_Trip_Tip_test

# production:
#   <<: *default
#   database: The_Trip_Tip_production
#   username: root
#   password:
#   host: 127.0.0.1
#   socket: /var/lib/mysql/mysql.sock

test: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: The_Trip_Tip_test
  username: <%= ENV.fetch("MYSQL_USERNAME") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD") %>
  host: <%= ENV.fetch("MYSQL_HOST") %>
  port: <%= ENV.fetch("MYSQL_PORT") %>
