default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: The_Trip_Tip_development

test:
  <<: *default
  database: The_Trip_Tip_test
  username: <%= ENV['DB_USERNAME'] || 'root' %>
  password: <%= ENV['DB_PASSWORD'] || 'password' %>
  host: <%= ENV['DB_HOST'] || 'db' %>

production:
  <<: *default
  database: The_Trip_Tip_production
  username: root
  password:
  host: 127.0.0.1
  socket: /var/lib/mysql/mysql.sock
