default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  host: 127.0.0.1

development:
  <<: *default
  database: The_Trip_Tip_development
  socket: /tmp/mysql.sock

test:
  <<: *default
  database: The_Trip_Tipsample_test
  socket: /tmp/mysql.sock

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOSTNAME'] %>
  pool: 5
  socket: /var/lib/mysql/mysql.sock
